version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5010:5000"
    restart: unless-stopped
    networks:
      - default
    volumes:
      - "./backend:/app/"
    env_file:
      - .env